# Generated by Django 2.2.2 on 2021-09-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='photol',
            new_name='photo3',
        ),
        migrations.AddField(
            model_name='diary',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真1'),
        ),
        migrations.AddField(
            model_name='diary',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真2'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新日時'),
        ),
    ]
